import pygame
import sees
import sees.Scene as Sc
import Walls
import Entity as E
import Tile as T
import GameScene as GS
import SceneLevelBoss2 as B2
from sees.TupleEnumTypes import SceneState

class SceneLevelBoss(GS.GameScene):
    def __init__(self):
        super().__init__((112, 160), (224, 16), (224, 144), (-16, -16), T.TileFacing.NORTH)
        self.level = "1-3"
        self._endframe = 0
        self.addWall((0, 0),Walls.WallType.TOP_LEFT, True)
        self.addWall((16, 0),Walls.WallType.TOP, True)
        self.addWall((32, 0),Walls.WallType.TOP, True)
        self.addWall((48, 0),Walls.WallType.TOP, True)
        self.addWall((64, 0),Walls.WallType.TOP, True)
        self.addWall((80, 0),Walls.WallType.TOP, True)
        self.addHole((96,0))
        self.addHole((144,0))
        self.addWall((160,0), Walls.WallType.TOP, True)
        self.addWall((176,0), Walls.WallType.TOP, True)
        self.addWall((192,0), Walls.WallType.TOP, True)
        self.addWall((208,0), Walls.WallType.TOP, True)
        self.addWall((224,0), Walls.WallType.TOP, True)
        self.addWall((240,0), Walls.WallType.TOP_RIGHT, True)
        self.addWall((240,16), Walls.WallType.RIGHT, True)
        self.addWall((240,32), Walls.WallType.RIGHT, True)
        self.addWall((240,48), Walls.WallType.RIGHT, True)
        self.addWall((240,64),Walls.WallType.RIGHT, True)
        self.addWall((240,80), Walls.WallType.RIGHT, True)
        self.addWall((240,96), Walls.WallType.RIGHT, True)
        self.addWall((240,112), Walls.WallType.RIGHT, True)
        self.addWall((240,128), Walls.WallType.RIGHT, True)
        self.addWall((240,144), Walls.WallType.RIGHT, True)
        self.addWall((240,160), Walls.WallType.RIGHT, True)
        self.addWall((240,176), Walls.WallType.BOTTOM_RIGHT, True)
        self.addWall((16,176), Walls.WallType.BOTTOM, True)
        self.addWall((32,176), Walls.WallType.BOTTOM, True)
        self.addWall((48,176), Walls.WallType.BOTTOM, True)
        self.addWall((64,176), Walls.WallType.BOTTOM, True)
        self.addWall((80,176), Walls.WallType.BOTTOM, True)
        self.addWall((96,176), Walls.WallType.BOTTOM, True)
        self.addWall((112,176), Walls.WallType.BOTTOM, True)
        self.addWall((128,176), Walls.WallType.BOTTOM, True)
        self.addWall((144,176), Walls.WallType.BOTTOM, True)
        self.addWall((160,176), Walls.WallType.BOTTOM, True)
        self.addWall((176,176), Walls.WallType.BOTTOM, True)
        self.addWall((192,176), Walls.WallType.BOTTOM, True)
        self.addWall((208,176), Walls.WallType.BOTTOM, True)
        self.addWall((224,176), Walls.WallType.BOTTOM, True)
        self.addWall((0,176) , Walls.WallType.BOTTOM_LEFT, True)
        self.addWall((0,16), Walls.WallType.LEFT, True)
        self.addWall((0,32), Walls.WallType.LEFT, True)
        self.addWall((0,48), Walls.WallType.LEFT, True)
        self.addWall((0,64), Walls.WallType.LEFT, True)
        self.addWall((0,80), Walls.WallType.LEFT, True)
        self.addWall((0,96), Walls.WallType.LEFT, True)
        self.addWall((0,112), Walls.WallType.LEFT, True)
        self.addWall((0,128), Walls.WallType.LEFT, True)
        self.addWall((0,144), Walls.WallType.LEFT, True)
        self.addWall((0,160), Walls.WallType.LEFT, True)

        self.addGround((16,16))
        self.addGround((16,32))
        self.addGround((16,48))
        self.addGround((16,64))
        self.addGround((16,80))
        self.addGround((16,96))
        self.addGround((16,112))
        self.addGround((16,128))
        self.addGround((16,144))
        self.addGround((16,160))
        self.addGround((32,16))
        self.addGround((32,32))

        self.addGround((32,80))
        self.addGround((32,96))
        self.addGround((32,112))
        self.addGround((32,128))
        self.addGround((32,144))
        self.addGround((48,16))
        self.addGround((48,32))
        self.addGround((48,48))
        self.addGround((48,80))
        self.addGround((48,96))
        self.addGround((48,112))
        self.addGround((48,128))
        self.addGround((48,144))
        self.addGround((48,160))
        self.addGround((64,16))
        self.addGround((64,32))
        self.addGround((64,48))
        self.addGround((64,64))
        self.addGround((64,80))
        self.addGround((64,96))
        self.addGround((64,112))
        self.addGround((64,128))
        self.addGround((64,144))
        self.addGround((64,160))
        self.addGround((80,16))
        self.addGround((80,32))
        self.addGround((80,48))
        self.addGround((80,64))
        self.addGround((80,80))
        self.addGround((80,96))
        self.addGround((80,112))
        self.addGround((80,128))
        self.addGround((80,144))
        self.addGround((80,160))
        self.addHole((96,16))
        self.addHole((96,32))
        self.addHole((96,48))
        self.addHole((96,64))
        self.addHole((96,80))
        self.addGround((96,112))
        self.addGround((96,128))
        self.addGround((96,144))
        self.addGround((96,160))

        self.addGround((112,32))
        self.addGround((112,48))
        self.addGround((112,64))
        self.addGround((112,80))
        self.addGround((128,32))
        self.addGround((128,48))
        self.addGround((128,64))
        self.addGround((128,80))
        
        self.addHole((112,96))
        self.addGround((112,112))
        self.addGround((112,128))
        self.addGround((112,144))
        self.addGround((112,160))
        self.addHole((128,96))
        self.addGround((128,112))
        self.addGround((128,128))
        self.addGround((128,144))
        self.addGround((128,160))
        self.addHole((144,16))
        self.addHole((144,32))
        self.addHole((144,48))
        self.addHole((144,64))
        self.addHole((144,80))
        self.addHole((144,96))
        self.addGround((144,112))
        self.addGround((144,128))
        self.addGround((144,144))
        self.addGround((144,160))
        self.addGround((160,16))
        self.addGround((160,32))
        self.addGround((160,48))
        self.addGround((160,64))
        self.addGround((160,80))
        self.addGround((160,96))
        self.addGround((160,112))
        self.addGround((160,128))
        self.addGround((160,144))
        self.addGround((160,160))
        self.addGround((176,16))
        self.addGround((176,32))
        self.addGround((176,48))
        self.addGround((176,64))
        self.addGround((176,80))
        self.addGround((176,96))
        self.addGround((176,112))
        self.addGround((192,16))
        self.addGround((192,32))
        self.addGround((192,48))
        self.addGround((192,64))
        self.addGround((192,80))
        self.addGround((192,96))
        self.addGround((192,112))
        self.addGround((192,128))
        self.addGround((192,144))
        self.addGround((192,160))
        self.addGround((208,16))
        self.addGround((208,32))
        self.addGround((208,48))
        self.addGround((208,64))
        self.addGround((208,80))
        self.addGround((208,96))
        self.addGround((208,112))
        self.addGround((208,128))
        self.addGround((208,144))
        self.addGround((208,160))
        self.addGround((224,16))
        self.addGround((224,32))
        self.addGround((224,48))
        self.addGround((224,64))
        self.addGround((224,80))
        self.addGround((224,96))
        self.addGround((224,112))
        self.addGround((224,128))
        self.addGround((224,144))
        self.addGround((224,160))
        self.addWall((96, 0),Walls.WallType.TOP_RIGHT, True)
        self.addWall((96, 16),Walls.WallType.RIGHT, True)
        self.addWall((96, 32),Walls.WallType.RIGHT, True)
        self.addWall((96, 48),Walls.WallType.RIGHT, True)
        self.addWall((96, 64),Walls.WallType.RIGHT, True)
        self.addWall((96, 80),Walls.WallType.RIGHT, True)
        self.addWall((96, 96),Walls.WallType.TOP_RIGHT, False)
        self.addWall((112, 96),Walls.WallType.TOP, True)
        self.addWall((128, 96),Walls.WallType.TOP, True)
        self.addWall((144, 96),Walls.WallType.TOP_LEFT, False)
        self.addWall((144, 0),Walls.WallType.TOP_LEFT, True)
        self.addWall((144, 16),Walls.WallType.LEFT, True)
        self.addWall((144, 32),Walls.WallType.LEFT, True)
        self.addWall((144, 48),Walls.WallType.LEFT, True)
        self.addWall((144, 64),Walls.WallType.LEFT, True)
        self.addWall((144, 80),Walls.WallType.LEFT, True)

        self.addBarrierAndButton((16, 16), (192, 144), True)
        self.addBarrierAndButton((16, 160), (224, 32), False)

        self.addDecoration((32, 0), GS.DecoTypes.ARMOIRE_FERMEE_HAUT)
        self.addDecoration((48, 0), GS.DecoTypes.ARMOIRE_OUVERTE_HAUT)
        self.addDecoration((64, 0), GS.DecoTypes.DOUBLE_PAPIER)
        self.addDecoration((80, 0), GS.DecoTypes.AFFICHE_ROUGE)
        self.addDecoration((160, 0), GS.DecoTypes.ARMOIRE_FERMEE_HAUT)
        self.addDecoration((176, 0), GS.DecoTypes.ARMOIRE_FERMEE_HAUT)
        self.addDecoration((160, 16), GS.DecoTypes.ARMOIRE_FERMEE_BAS)
        self.addDecoration((176, 16), GS.DecoTypes.ARMOIRE_FERMEE_BAS)
        self.addDecoration((192, 0), GS.DecoTypes.DOUBLE_PAPIER)
        self.addDecoration((224, 0), GS.DecoTypes.AFFICHE_ROUGE)
        self.addDecoration((32, 16), GS.DecoTypes.ARMOIRE_FERMEE_BAS)
        self.addDecoration((48, 16), GS.DecoTypes.ARMOIRE_OUVERTE_BAS)
        self.addDecoration((64, 16), GS.DecoTypes.BUREAU_FACE)
        self.addDecoration((80, 16), GS.DecoTypes.BUREAU_FACE)
        self.addDecoration((64, 32), GS.DecoTypes.SIMPLE_PAPIER)
        self.addDecoration((80, 32), GS.DecoTypes.CHAISE)
        self.addDecoration((80, 48), GS.DecoTypes.CARTONS)
        self.addSecondaryCube((16,48))
        self.addHole((32, 48))
        self.addHole((32, 64))
        self.addHole((48, 64))
        self.addWallBlock((80, 64))
        self.addDecoration((80, 80), GS.DecoTypes.FLAQUE)
        self.addWallBlock((64, 64))
        self.addWallBlock((16, 64))
        self.addDecoration((112, 96), GS.DecoTypes.DOUBLE_PAPIER)
        self.addDecoration((128, 96), GS.DecoTypes.DOUBLE_PAPIER)
        self.addDecoration((192, 16), GS.DecoTypes.CARTONS)
        self.addWallBlock((208, 16))
        self.addWallBlock((208, 32))
        self.addDecoration((160, 32), GS.DecoTypes.ARMOIRE_DOS_HAUT)
        self.addDecoration((160, 48), GS.DecoTypes.ARMOIRE_DOS_BAS)
        self.addDecoration((176, 64), GS.DecoTypes.SIMPLE_PAPIER)
        self.addDecoration((160, 80), GS.DecoTypes.BUREAU_DROITE)
        self.addSecondaryCube((224,80))
        self.addDecoration((224, 112), GS.DecoTypes.FLAQUE)
        self.addWallBlock((224, 128))
        self.addWallBlock((208, 128))
        self.addWallBlock((192, 128))
        self.addWallBlock((192, 160))
        self.addHole((176, 128))
        self.addHole((176, 144))
        self.addHole((176, 160))
        self.addDecoration((144, 112), GS.DecoTypes.BUREAU_GAUCHE)
        self.addSecondaryCube((128,112))
        self.addDecoration((144, 128), GS.DecoTypes.BUREAU_GAUCHE)
        self.addDecoration((96, 112), GS.DecoTypes.BUREAU_DROITE)
        self.addDecoration((96, 128), GS.DecoTypes.BUREAU_DROITE)
        self.addDecoration((112, 112), GS.DecoTypes.CHAISE)
        self.addDecoration((112, 128), GS.DecoTypes.SIMPLE_PAPIER)
        self.addDecoration((80, 112), GS.DecoTypes.SIMPLE_PAPIER)
        self.addDecoration((16, 112), GS.DecoTypes.CARTONS)
        self.addDecoration((32, 112), GS.DecoTypes.CARTONS)
        self.addWallBlock((16, 128))
        self.addWallBlock((32, 128))
        self.addWallBlock((16, 144))
        self.addWallBlock((32, 144))
        self.addWallBlock((48, 144))
        self.addHole((32, 160))
        self.addAirCannon((128,80))
        self.addAirCannon((112,80))

        self.addEntryDoor((112,176),T.TileFacing.SOUTH)

        self._boss = E.EntityBoss1(self, (112, 48))
        self._tiles.append(self._boss)
        self._blinking.append(self._boss)
    
    def restartScene(self):
        Sound= pygame.mixer.Sound("SoundTrack/Traverser_une_porte.wav")
        Sound.play()
        self.musicOff()
        nextScene = SceneLevelBoss()
        nextScene.setInputs(self.getInputs())
        self._nextScene = nextScene
        self.setState(SceneState.CHANGE_SCENE)
        
    def mapLogic(self):
        if self._door.getOpened() == True and self._endframe == 0:
            inputs = self.getInputs()
            self.setInputs(None)
            self._player.setOrientation(T.TileFacing.SOUTH)
            Sound= pygame.mixer.Sound("SoundTrack/Accomplished_4.wav")
            Sound.play()
            self.musicOff()
            nextScene = B2.SceneLevelBoss2(self._player.getPos())
            nextScene.setInputs(inputs)
            self._nextScene = nextScene
            for cannon in self._aircannons:
                cannon.enableAir()
            self._endframe += 1
        if self._endframe > 0 and self._endframe < 90:
            self._endframe += 1
        if self._endframe == 30:
            self._boss.setPos((112, 40))
        if self._endframe == 60:
            self._boss.setPos((112, 32))
        if self._endframe == 90:
            self.setState(SceneState.CHANGE_SCENE)
        